
//============================ UPLOADING PHOTOS ===========================

export const USER_UPLOAD_PHOTO_START = 'USER_UPLOAD_PHOTO_START';
export const USER_UPLOAD_PHOTO_SUCCESS = 'USER_UPLOAD_PHOTO_SUCCESS';
export const USER_UPLOAD_PHOTO_ERROR = 'USER_UPLOAD_PHOTO_ERROR';

export const USER_PHOTO_REMOVE_SUCCESS = 'USER_PHOTO_REMOVE_SUCCESS';
export const USER_PHOTO_REMOVE_ERROR = 'USER_PHOTO_REMOVE_ERROR';

//==========================// UPLOADING PHOTOS ===========================

//============================ PROFILE SIMPLE DATA ========================

export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_ERROR = 'USER_UPDATE_PROFILE_ERROR';

//==========================// PROFILE SIMPLE DATA ========================

//============================ LANGUAGE SKILLS ============================

export const USER_LANGUAGE_SKILL_CREATE_SUCCESS = 'USER_LANGUAGE_SKILL_CREATE_SUCCESS';
export const USER_LANGUAGE_SKILL_CREATE_ERROR = 'USER_LANGUAGE_SKILL_CREATE_ERROR';

export const USER_LANGUAGE_SKILL_UPDATE_SUCCESS = 'USER_LANGUAGE_SKILL_UPDATE_SUCCESS';
export const USER_LANGUAGE_SKILL_UPDATE_ERROR = 'USER_LANGUAGE_SKILL_UPDATE_ERROR';

export const USER_LANGUAGE_SKILL_REMOVE_SUCCESS = 'USER_LANGUAGE_SKILL_REMOVE_SUCCESS';
export const USER_LANGUAGE_SKILL_REMOVE_ERROR = 'USER_LANGUAGE_SKILL_REMOVE_ERROR';

//==========================// LANGUAGE SKILLS ============================